{include file="../application/index/view/public/header.phtml" /}
<div class="page-container page-width">
  {include file="../application/index/view/public/sidebar.phtml" /}
  <div class="main-content">
    {include file="../application/index/view/public/info.phtml" /}
    <ol class="breadcrumb bc-3">
      <li>
        <a href="/admin/index"><i class="entypo-home"></i>首页</a>
      </li>
      <li class="active">
        <strong>音乐列表</strong>
      </li>
    </ol>
    <div class="dataTables_wrapper form-inline">
      <div class="row screen-sm">
        <div class="col-lg-12">
          <div class="pull-right">
            <a class="btn btn-green btn-sm" id="showAddMusicModal">添加音乐</a>
          </div>
        </div>
      </div>
    </div>
    <div class="table-responsive">
      <table class="table table-bordered table-striped datatable dataTable text-nowrap custom-table-font-size">
        <thead class="th-color">
          <tr>
            <th>歌曲ID</th>
            <th>歌曲名称</th>
            <th>歌手</th>
            <th>专辑名称</th>
            <th>语言</th>
            <th>发布时间</th>
            <th>播放量</th>
            <th>喜欢数量</th>
            <th>评论人数</th>
            <th>总评分</th>
            <th>被搜索次数</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
          <?php if(!empty($pager['data'])):?>
            <?php foreach ($pager['data'] as $key=>$data):?>
              <tr role="row">
                <td><?php echo $data['song_id'];?></td>
                <td><?php echo $data['song_name'];?></td>
                <td><?php echo $data['singer'];?></td>
                <td><?php echo $data['album_name'];?></td>
                <td><?php echo $data['language'];?></td>
                <td><?php echo $data['issue_time'];?></td>
                <td><?php echo $data['played'];?></td>
                <td><?php echo $data['love'];?></td>
                <td><?php echo $data['comments_num'];?></td>
                <td><?php echo $data['comments_score'];?></td>
                <td><?php echo $data['select_num'];?></td>
                <th>
                  <a class="btn btn-info btn-sm editMusic" data-id="<?php echo $data['song_id'];?>">修改</a>
                  <a class="btn btn-red btn-sm delMusic" data-id="<?php echo $data['song_id'];?>">删除</a>
                </th>
              </tr>
            <?php endforeach;?>
          <?php else:?>
            <td colspan="12" style="text-align: center;">暂无信息</>
          <?php endif;?>
        </tbody>
      </table>
    </div>
    {include file="../application/index/view/public/pager.phtml" /}
  </div>

  <!-- 添加弹窗 start -->
  <div class="modal fade" id="addMusicModal">
    <div class="modal-dialog custom-modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4>添加音乐</h4>
        </div>
        <div class="modal-body">
          <form class="form-horizontal form-groups-bordered form-static" enctype="multipart/form-data" id="addForm">
            <div class="form-group">
              <label class="control-label col-md-3" for="song_name">歌曲名称</label>
              <div class="col-md-6">
                <input type="text" name="song_name" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="singer">歌手</label>
              <div class="col-md-6">
                <input type="text" name="singer" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="album_id">专辑Id</label>
              <div class="col-md-6">
                <input type="text" name="album_id" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="language">语言</label>
              <div class="col-md-6">
                <input type="text" name="language" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="issue_time">发布时间</label>
              <div class="col-md-6">
                <input type="text" class="form-control datepicker" data-format="yyyy-MM-dd" data-callback="rangeChange" name="issue_time">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_old">老歌权重</label>
              <div class="col-md-6">
                <input type="text" name="is_old" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_popular">流行音乐权重</label>
              <div class="col-md-6">
                <input type="text" name="is_popular" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_dj">Dj权重</label>
              <div class="col-md-6">
                <input type="text" name="is_dj" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_classical">古典音乐权重</label>
              <div class="col-md-6">
                <input type="text" name="is_classical" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_flok">民谣权重</label>
              <div class="col-md-6">
                <input type="text" name="is_flok" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_rap">说唱权重</label>
              <div class="col-md-6">
                <input type="text" name="is_rap" class="form-control">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_new">是否新歌</label>
              <div class="col-sm-9">
                <label class="radio-inline">
                  <input type="radio" name="is_new" value="0">否
                </label>
                <label class="radio-inline">
                  <input type="radio" name="is_new" value="1" checked>是
                </label>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="lyrics">歌词</label>
              <div class="col-md-6">
                <textarea class="form-control" name="lyrics"></textarea>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="img">歌曲封面</label>
              <div class="col-md-6">
                <input type="file" name="" id="addSongPicture">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="video">歌曲源文件</label>
              <div class="col-md-6">
                <input type="file" name="" id="addSongVideo">
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-info" id="addMusic">添加</button>
        </div>
      </div>
    </div>
  </div>
  <!-- 添加弹窗 end -->

  <!-- 编辑弹窗 start -->
  <div class="modal fade" id="editMusicModal">
    <div class="modal-dialog custom-modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4>添加音乐</h4>
        </div>
        <div class="modal-body">
          <form class="form-horizontal form-groups-bordered form-static" enctype="multipart/form-data" id="editForm">
            <div class="form-group">
              <input type="hidden" name="song_id" class="form-control" id="song_id">
              <label class="control-label col-md-3" for="song_name">歌曲名称</label>
              <div class="col-md-6">
                <input type="text" name="song_name" class="form-control" id="song_name">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="singer">歌手</label>
              <div class="col-md-6">
                <input type="text" name="singer" class="form-control" id="singer">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="album_id">专辑Id</label>
              <div class="col-md-6">
                <input type="text" name="album_id" class="form-control" id="album_id">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="language">语言</label>
              <div class="col-md-6">
                <input type="text" name="language" class="form-control" id="language">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="issue_time">发布时间</label>
              <div class="col-md-6">
                <input type="text" class="form-control datepicker" data-format="yyyy-MM-dd" data-callback="rangeChange" name="issue_time" id="issue_time">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_old">老歌权重</label>
              <div class="col-md-6">
                <input type="text" name="is_old" class="form-control" id="is_old">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_popular">流行音乐权重</label>
              <div class="col-md-6">
                <input type="text" name="is_popular" class="form-control" id="is_popular">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_dj">Dj权重</label>
              <div class="col-md-6">
                <input type="text" name="is_dj" class="form-control" id="is_dj">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_classical">古典音乐权重</label>
              <div class="col-md-6">
                <input type="text" name="is_classical" class="form-control" id="is_classical">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_flok">民谣权重</label>
              <div class="col-md-6">
                <input type="text" name="is_flok" class="form-control" id="is_flok">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_rap">说唱权重</label>
              <div class="col-md-6">
                <input type="text" name="is_rap" class="form-control" id="is_rap">
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="is_new">是否新歌</label>
              <div class="col-sm-9">
                <label class="radio-inline">
                  <input type="radio" name="is_new" value="0">否
                </label>
                <label class="radio-inline">
                  <input type="radio" name="is_new" value="1" checked>是
                </label>
              </div>
            </div>
            <div class="form-group">
              <label class="control-label col-md-3" for="lyrics">歌词</label>
              <div class="col-md-6">
                <textarea class="form-control" name="lyrics" id="lyrics"></textarea>
              </div>
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button class="btn btn-info" id="editMusic">添加</button>
        </div>
      </div>
    </div>
  </div>
  <!-- 添加弹窗 end -->
</div>
<script type="text/javascript">
  (() => {
    // 添加音乐
    $('#showAddMusicModal').click(() => {
      $('#addMusicModal').modal('show');
    });
    $('#addMusic').click(() => {
      const params = $('#addForm').serializeArray();
      let formData = new FormData();
      formData.append("songPicture", $("#addSongPicture")[0].files[0]);
      formData.append("songOrigin", $("#addSongVideo")[0].files[0]);
      for (let i in params) {
        formData.append(params[i].name, params[i].value)
      }
      $.ajax({
        url: "/admin/music/add",
        type: "post",
        data: formData,
        async: true,
        cache: false,
        contentType: false,
        processData: false,
        success: function(res){
          if (res.status === true) {
            location.reload();
          } else {
            alert(res);
          }
        },
        error: function(err){
          alert(res);
        }
      })
    });
    // 获取商品详情
    $('.editMusic').click(function() {
      const params = {
        song_id: $(this).attr('data-id')
      }
      $.post('/admin/music/getsong', params, (res) => {
        for (let i in res.data) {
          if ($('#' + i)) {
            $('#' + i).val(res.data[i])
          }
        }
        $('#editMusicModal').modal('show');
      });
    });
    // 修改商品信息
    $('#editMusic').click(function() {
      const params = $('#editForm').serializeArray();
      $.post('/admin/music/update', params, (res) => {
        if (res.status === true) {
          location.reload();
        } else {
          alert(res.msg);
        }
      });
    });
    // 删除音乐
    $('.delMusic').click(function() {
      if (confirm('确定删除该音乐嘛？')) {
        const params = {
          song_id: $(this).attr('data-id')
        }
        $.post('/admin/music/delete', params, (res) => {
          if (res.status === true) {
            location.reload();
          } else {
            alert(res.msg);
          }
        })
      }
    });
  })();
</script>
{include file="../application/index/view/public/footer.phtml" /}